### PR TITLE
Feature/img alt detection

### PR DESCRIPTION
**Pull request by Andy-set-studio**
Found it on this thread: https://twitter.com/addyosmani/status/1223873759213314050

It's a great idea

### CODE REVIEW

**Comment by nstickney** [comment]
This ...doesn't seem like a great idea.

I may be using the reset wrong; is it not meant for production? This seems like a great idea in a dev environment but blurring images in production doesn't help anyone.

**Comment by NemoStein** [comment]
I don't think this is a good idea, either.
Considering that most images on the web are decorative and that this reset can be installed by NPM/Yarn, this can break a lot of unsuspecting projects.

**Comment by stramel** [comment]
Maybe if we also add a `:not([aria-hidden])` to it as well?

**Comment by Andy-set-studio** [comment]
An image with an empty alt tag will not be affected. Only inaccessible images will be affected. Tools that add images that don’t put even an empty alt tag are not fit for production anyway.

Even with aria hidden, images need to have an empty alt because older assistive tech can have issues with aria roles.

**Pull request merged**
